# Generated by Django 5.2.12 on 2026-06-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='certifications/'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='certificate_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certifications/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='projectscreenshot',
            name='image',
            field=models.ImageField(upload_to='screenshots/'),
        ),
    ]
